# === docker-compose.yml ===
version: '3.8'

services:
  ml_api:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    networks:
      - ml_net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ml_net

networks:
  ml_net:
    driver: bridge
